version: '3'
services:
  curr-app:
    image: golang:latest
    container_name: currency-converter-app
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=postgres://user:password@curr-db:5432/currency_converter
    depends_on:
      - curr-db

  curr-db:
    image: postgres:latest
    container_name: currency-converter-db
    environment:
      POSTGRES_DB: currency_converter
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5433'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
